/// @file       /src/dsf/headers/FirstOrderDynamics.hpp
/// @brief      Defines the FirstOrderDynamics class.
///
/// @details    This file contains the definition of the FirstOrderDynamics class.
///             The FirstOrderDynamics class represents the dynamics of the network. It is templated by the type
///             of the graph's id and the type of the graph's capacity.
///             The graph's id and capacity must be unsigned integral types.

#pragma once

#include <algorithm>
#include <atomic>
#include <cassert>
#include <cmath>
#include <concepts>
#include <exception>
#include <format>
#include <fstream>
#include <iomanip>
#include <numeric>
#include <optional>
#include <random>
#include <span>
#include <sstream>
#include <iostream>
#include <thread>
#include <tuple>
#include <unordered_map>
#include <variant>
#include <vector>

#include <tbb/tbb.h>
#include <spdlog/spdlog.h>

#include "../base/Dynamics.hpp"
#include "Agent.hpp"
#include "Itinerary.hpp"
#include "RoadNetwork.hpp"
#include "../utility/Typedef.hpp"

static constexpr auto CACHE_FOLDER = "./.dsfcache/";
static constexpr auto U_TURN_PENALTY_FACTOR = 0.1;

namespace dsf::mobility {
  /// @brief The method for inserting agents into the network
  enum class AgentInsertionMethod : uint8_t {
    RANDOM = 0,  // Agents spawn randomly in the network and travel with no destination
    ODS = 1,     // Agents are generated according to the provided OD pairs
    RANDOM_ODS =
        2,  // Agents are generated by randomly selecting their origin and destination according to the weights
  };
  /// @brief The FirstOrderDynamics class represents the dynamics of the network.
  class FirstOrderDynamics : public Dynamics<RoadNetwork> {
    std::vector<Id> m_nodeIndices;
    std::vector<std::unique_ptr<Agent>> m_agents;
    std::unordered_map<Id, std::shared_ptr<Itinerary>> m_itineraries;
    std::vector<std::tuple<Id, double>> m_originNodes;
    std::vector<std::tuple<Id, double>> m_destinationNodes;
    std::vector<std::tuple<Id, Id, double>> m_ODs;
    tbb::concurrent_unordered_map<Id, std::size_t> m_originCounts;
    tbb::concurrent_unordered_map<Id, std::size_t> m_destinationCounts;
    std::atomic<std::size_t> m_nAgents{0}, m_nAddedAgents{0}, m_nInsertedAgents{0},
        m_nKilledAgents{0}, m_nArrivedAgents{0};
    std::function<double(std::unique_ptr<Street> const&)> m_speedFunction;
    std::string m_speedFunctionDescription;

  protected:
    std::unordered_map<Id, std::unordered_map<Id, size_t>> m_turnCounts;
    std::unordered_map<Id, std::array<long, 4>> m_turnMapping;
    tbb::concurrent_unordered_map<Id, std::unordered_map<Direction, double>>
        m_queuesAtTrafficLights;
    tbb::concurrent_vector<std::pair<double, double>> m_travelDTs;
    std::time_t m_previousOptimizationTime{0};

  protected:
    std::function<double(std::unique_ptr<Street> const&)> m_weightFunction;
    std::optional<double> m_errorProbability{std::nullopt};
    std::optional<double> m_passageProbability{std::nullopt};
    std::optional<double> m_meanTravelDistance{std::nullopt};
    std::optional<std::time_t> m_meanTravelTime{std::nullopt};
    std::optional<Delay> m_dataUpdatePeriod;
    bool m_bCacheEnabled;
    PathWeight m_pathWeight = PathWeight::TRAVELTIME;
    double m_weightTreshold;
    std::optional<double> m_timeToleranceFactor{std::nullopt};
    bool m_forcePriorities{false};
    // Saving variables
    std::optional<std::time_t> m_savingInterval{std::nullopt};
    bool m_bSaveStreetData{false};
    bool m_bSaveTravelData{false};
    bool m_bSaveAverageStats{false};

  private:
    /// @brief Kill an agent
    /// @param pAgent A std::unique_ptr to the agent to kill
    std::unique_ptr<Agent> m_killAgent(std::unique_ptr<Agent> pAgent);
    /// @brief Update the path of a single itinerary using Dijsktra's algorithm
    /// @param pItinerary An std::shared_ptr to the itinerary
    void m_updatePath(std::shared_ptr<Itinerary> const& pItinerary);

    void m_addAgentsRandom(std::size_t nAgents);
    void m_addAgentsODs(std::size_t nAgents);
    void m_addAgentsRandomODs(std::size_t nAgents);

    /// @brief Get the next street id
    /// @param pAgent A std::unique_ptr to the agent
    /// @param pNode A std::unique_ptr to the current node
    /// @return Id The id of the randomly selected next street
    std::optional<Id> m_nextStreetId(const std::unique_ptr<Agent>& pAgent,
                                     const std::unique_ptr<RoadJunction>& pNode);
    /// @brief Evolve a street
    /// @param pStreet A std::unique_ptr to the street
    /// @param reinsert_agents If true, the agents are reinserted in the simulation after they reach their destination
    /// @details If possible, removes the first agent of the street's queue, putting it in the destination node.
    /// If the agent is going into the destination node, it is removed from the simulation (and then reinserted if reinsert_agents is true)
    void m_evolveStreet(std::unique_ptr<Street> const& pStreet, bool reinsert_agents);
    /// @brief If possible, removes one agent from the node, putting it on the next street.
    /// @param pNode A std::unique_ptr to the node
    void m_evolveNode(const std::unique_ptr<RoadJunction>& pNode);
    /// @brief Evolve the agents.
    /// @details Puts all new agents on a street, if possible, decrements all delays
    /// and increments all travel times.
    void m_evolveAgents();

    void m_trafficlightSingleTailOptimizer(double const& beta,
                                           std::optional<std::ofstream>& logStream);

    inline double m_streetEstimatedTravelTime(
        std::unique_ptr<Street> const& pStreet) const {
      return pStreet->length() / m_speedFunction(pStreet);
    };

    /// @brief Initialize the street data table.
    /// This table contains the data of each street. Columns are:
    /// - id: The entry id (auto-incremented)
    /// - simulation_id: The simulation id
    /// - datetime: The datetime of the data entry
    /// - time_step: The time step of the data entry
    /// - street_id: The id of the street
    /// - coil: The name of the coil on the street (can be null)
    /// - density_vpk: The density in vehicles per kilometer
    /// - avg_speed_kph: The average speed in kilometers per hour
    /// - std_speed_kph: The standard deviation of the speed in kilometers per hour
    /// - n_observations: The number of speed observations used to compute avg/std (0 if none)
    /// - counts: The counts of the coil sensor (can be null)
    /// - queue_length: The length of the queue on the street
    void m_initStreetTable() const;
    /// @brief Initialize the average stats table.
    /// This table contains the average stats of the simulation at each time step. Columns are:
    /// - id: The entry id (auto-incremented)
    /// - simulation_id: The simulation id
    /// - datetime: The datetime of the data entry
    /// - time_step: The time step of the data entry
    /// - n_ghost_agents: The number of ghost agents
    /// - n_agents: The number of agents
    /// - mean_speed_kph: The mean speed of the agents in kilometers per hour
    /// - std_speed_kph: The standard deviation of the speed of the agents in kilometers per hour
    /// - mean_density_vpk: The mean density of the streets in vehicles per kilometer
    /// - std_density_vpk: The standard deviation of the density of the streets in vehicles per kilometer
    void m_initAvgStatsTable() const;
    /// @brief Initialize the travel data table.
    /// This table contains the travel data of the agents. Columns are:
    /// - id: The entry id (auto-incremented)
    /// - simulation_id: The simulation id
    /// - datetime: The datetime of the data entry
    /// - time_step: The time step of the data entry
    /// - distance_m: The distance travelled by the agent in meters
    /// - travel_time_s: The travel time of the agent in seconds
    void m_initTravelDataTable() const;

    /// @brief Dump simulation metadata into the database.
    /// @details Ensures the `simulations` table exists and inserts one row with the
    /// current simulation configuration. If no database is connected, this function
    /// returns immediately.
    ///
    /// Stored fields are:
    /// - id
    /// - name
    /// - speed_function (identified by a string description, e.g. "LINEAR(alpha=0.5)" or "CUSTOM")
    /// - weight_function
    /// - weight_threshold
    /// - error_probability
    /// - passage_probability
    /// - mean_travel_distance_m
    /// - mean_travel_time_s
    /// - stagnant_tolerance_factor
    /// - force_priorities
    /// - save_avg_stats
    /// - save_road_data
    /// - save_travel_data
    void m_dumpSimInfo() const;

    void m_dumpNetwork() const;

  public:
    /// @brief Construct a new FirstOrderDynamics object
    /// @param graph The graph representing the network
    /// @param useCache If true, the cache is used (default is false)
    /// @param seed The seed for the random number generator (default is std::nullopt)
    FirstOrderDynamics(RoadNetwork& graph,
                       bool useCache = false,
                       std::optional<unsigned int> seed = std::nullopt);

    /// @brief Set the error probability
    /// @param errorProbability The error probability
    /// @throw std::invalid_argument If the error probability is not between 0 and 1
    void setErrorProbability(double errorProbability);
    /// @brief Set the passage probability
    /// @param passageProbability The passage probability
    /// @details The passage probability is the probability of passing through a node
    ///   It is useful in the case of random agents
    void setPassageProbability(double passageProbability);
    /// @brief Set the time tolerance factor for killing stagnant agents.
    ///   An agent will be considered stagnant if it has not moved for timeToleranceFactor * std::ceil(street_length / street_maxSpeed) time units.
    /// @param timeToleranceFactor The time tolerance factor
    /// @throw std::invalid_argument If the time tolerance factor is not positive
    void killStagnantAgents(double timeToleranceFactor = 3.);
    /// @brief Set the weight function
    /// @param pathWeight The dsf::PathWeight function to use for the pathfinding
    /// @param weightThreshold The weight threshold for updating the paths (default is std::nullopt)
    void setWeightFunction(PathWeight const pathWeight,
                           std::optional<double> weightThreshold = std::nullopt);
    /// @brief Set the speed function. Options are:
    /// - (LINEAR, alpha): speed = max_speed * (1 - alpha * density), where alpha is a parameter in [0, 1)
    /// - (CUSTOM, func): speed = func(pointer to a street), where func is a callable provided by the user that takes the street's pointer.
    template <typename... TArgs>
    void setSpeedFunction(SpeedFunction const speedFunction, TArgs&&... args);
    /// @brief Set the force priorities flag
    /// @param forcePriorities The flag
    /// @details If true, if an agent cannot move to the next street, the whole node is skipped
    inline void setForcePriorities(bool forcePriorities) noexcept {
      m_forcePriorities = forcePriorities;
    }
    /// @brief Set the data update period.
    /// @param dataUpdatePeriod Delay, The period
    /// @details Some data, i.e. the street queue lengths, are stored only after a fixed amount of time which is represented by this variable.
    inline void setDataUpdatePeriod(Delay const dataUpdatePeriod) noexcept {
      m_dataUpdatePeriod = dataUpdatePeriod;
    }
    /// @brief Set the mean distance travelled by a random agent. The distance will be sampled from an exponential distribution with this mean.
    /// @param meanTravelDistance The mean distance
    /// @throw std::invalid_argument If the mean distance is negative
    inline void setMeanTravelDistance(double const meanTravelDistance) {
      meanTravelDistance > 0. ? m_meanTravelDistance = meanTravelDistance
                              : throw std::invalid_argument(
                                    "FirstOrderDynamics::setMeanTravelDistance: "
                                    "meanTravelDistance must be positive");
    };
    /// @brief Set the mean travel time for random agents. The travel time will be sampled from an exponential distribution with this mean.
    /// @param meanTravelTime The mean travel time
    inline void setMeanTravelTime(std::time_t const meanTravelTime) noexcept {
      m_meanTravelTime = meanTravelTime;
    };
    /// @brief Set the origin nodes. If the provided map is empty, the origin nodes are set using the streets' stationary weights.
    /// NOTE: the default stationary weights are 1.0 so, if not set, this is equivalent to setting uniform weights.
    /// @param originNodes The origin nodes
    void setOriginNodes(std::unordered_map<Id, double> const& originNodes = {});
    /// @brief Set the destination nodes
    /// @param destinationNodes The destination nodes
    void setDestinationNodes(std::unordered_map<Id, double> const& destinationNodes);
    /// @brief Set the destination nodes
    /// @param destinationNodes The destination nodes (as an initializer list)
    void setDestinationNodes(std::initializer_list<Id> destinationNodes);
    /// @brief Set the origin-destination pairs with their associated weights
    /// @param ODs A vector of tuples (origin node id, destination node id, weight)
    void setODs(std::vector<std::tuple<Id, Id, double>> const& ODs);
    /// @brief Set the destination nodes
    /// @param destinationNodes A container of destination nodes ids
    /// @details The container must have a value_type convertible to Id and begin() and end() methods
    template <typename TContainer>
      requires(std::is_convertible_v<typename TContainer::value_type, Id>)
    void setDestinationNodes(TContainer const& destinationNodes);

    /// @brief Initialize the turn counts map
    /// @throws std::runtime_error if the turn counts map is already initialized
    void initTurnCounts();
    /// @brief Reset the turn counts map values to zero
    /// @throws std::runtime_error if the turn counts map is not initialized
    void resetTurnCounts();
    /// @brief Enable data saving to the database
    /// @param savingInterval The interval at which save the data (in time steps). If zero, saves data at the next time step and then disables saving (working like a manual trigger).
    /// @param saveAverageStats If true, saves the average stats of the simulation (default is false)
    /// @param saveStreetData If true, saves the street data (default is false)
    /// @param saveTravelData If true, saves the travel data of the agents (default is false)
    void saveData(std::time_t const savingInterval,
                  bool const saveAverageStats = false,
                  bool const saveStreetData = false,
                  bool const saveTravelData = false);

    /// @brief Update the paths of the itineraries based on the given weight function
    /// @param throw_on_empty If true, throws an exception if an itinerary has an empty path (default is true)
    /// If false, removes the itinerary with empty paths and the associated node from the origin/destination nodes
    /// @throws std::runtime_error if throw_on_empty is true and an itinerary has an empty path
    void updatePaths(bool const throw_on_empty = true);
    /// @brief Add agents uniformly on the road network
    /// @param nAgents The number of agents to add
    /// @param itineraryId The id of the itinerary to use (default is std::nullopt)
    /// @throw std::runtime_error If there are no itineraries
    void addAgentsUniformly(std::size_t nAgents,
                            std::optional<Id> itineraryId = std::nullopt);

    /// @brief Add an agent to the simulation
    /// @param agent std::unique_ptr to the agent
    void addAgent(std::unique_ptr<Agent> agent);

    template <typename... TArgs>
      requires(std::is_constructible_v<Agent, Id, std::time_t, TArgs...>)
    void addAgent(TArgs&&... args);

    template <typename... TArgs>
      requires(std::is_constructible_v<Agent, Id, std::time_t, TArgs...>)
    void addAgents(std::size_t const nAgents, TArgs&&... args);
    /// @brief Add agents to the simulation
    /// @param nAgents The number of agents to add
    /// @param mode The method to use for adding the agents.Possible values are:
    /// - ODS: Agents are generated according to the provided OD pairs
    /// - RANDOM: Agents spwan randomly in the network and travel with no destination
    /// - RANDOM_ODS: Agents are generated by randomly selecting their origin and destination according to the weights
    void addAgents(std::size_t const nAgents, AgentInsertionMethod const mode);

    /// @brief Add an itinerary
    /// @param ...args The arguments to construct the itinerary
    /// @details The arguments must be compatible with any constructor of the Itinerary class
    template <typename... TArgs>
      requires(std::is_constructible_v<Itinerary, TArgs...>)
    void addItinerary(TArgs&&... args);
    /// @brief Add an itinerary
    /// @param itinerary std::unique_ptr to the itinerary
    /// @throws std::invalid_argument If the itinerary already exists
    /// @throws std::invalid_argument If the itinerary's destination is not a node of the graph
    void addItinerary(std::shared_ptr<Itinerary> itinerary);

    /// @brief Evolve the simulation
    /// @details Evolve the simulation by moving the agents and updating the travel times.
    /// In particular:
    /// - Move the first agent of each street queue, if possible, putting it in the next node
    /// - Move the agents from each node, if possible, putting them in the next street and giving them a speed.
    /// If the error probability is not zero, the agents can move to a random street.
    /// If the agent is in the destination node, it is removed from the simulation (and then reinserted if reinsert_agents is true)
    /// - Cycle over agents and update their times
    /// @param reinsert_agents If true, the agents are reinserted in the simulation after they reach their destination
    void evolve(bool const reinsert_agents = false);
    /// @brief Optimize the traffic lights by changing the green and red times
    /// @param optimizationType TrafficLightOptimization, The type of optimization. Default is DOUBLE_TAIL
    /// @param logFile The file into which write the logs (default is empty, meaning no logging)
    /// @param percentage double, the maximum amount (percentage) of the green time to change (default is 0.3)
    /// @param threshold double, The ratio between the self-density and neighbour density to trigger the non-local optimization (default is 1.3)
    /// @details The local optimization is done by changing the green time of each traffic light, trying to make it proportional to the
    ///    queue lengths at each phase. The non-local optimization is done by synchronizing the traffic lights which are congested over threshold.
    void optimizeTrafficLights(
        TrafficLightOptimization optimizationType = TrafficLightOptimization::DOUBLE_TAIL,
        const std::string& logFile = std::string(),
        double const percentage = 0.3,
        double const threshold = 1.3);

    /// @brief Get the itineraries
    /// @return const std::unordered_map<Id, Itinerary>&, The itineraries
    inline auto const& itineraries() const noexcept { return m_itineraries; }
    /// @brief Get the origin nodes of the graph
    /// @return std::vector<std::tuple<Id, double>> const& The origin nodes of the graph
    inline std::vector<std::tuple<Id, double>> const& originNodes() const noexcept {
      return m_originNodes;
    }
    /// @brief Get the origin nodes of the graph
    /// @return std::vector<std::tuple<Id, double>>& The origin nodes of the graph
    inline std::vector<std::tuple<Id, double>>& originNodes() noexcept {
      return m_originNodes;
    }
    /// @brief Get the destination nodes of the graph
    /// @return std::vector<std::tuple<Id, double>> const& The destination nodes of the graph
    inline std::vector<std::tuple<Id, double>> const& destinationNodes() const noexcept {
      return m_destinationNodes;
    }
    /// @brief Get the destination nodes of the graph
    /// @return std::vector<std::tuple<Id, double>>>& The destination nodes of the graph
    inline std::vector<std::tuple<Id, double>>& destinationNodes() noexcept {
      return m_destinationNodes;
    }
    /// @brief Get the agents
    /// @return const std::unordered_map<Id, Agent<Id>>&, The agents
    inline const std::vector<std::unique_ptr<Agent>>& agents() const noexcept {
      return m_agents;
    }
    /// @brief Get the number of agents currently in the simulation
    /// @return std::size_t The number of agents
    inline auto nAgents() const { return m_nAgents.load(); };

    /// @brief Get the mean travel time of the agents in \f$s\f$
    /// @param clearData If true, the travel times are cleared after the computation
    /// @return Measurement<double> The mean travel time of the agents and the standard deviation
    Measurement<double> meanTravelTime(bool clearData = false);
    /// @brief Get the mean travel distance of the agents in \f$m\f$
    /// @param clearData If true, the travel distances are cleared after the computation
    /// @return Measurement<double> The mean travel distance of the agents and the standard deviation
    Measurement<double> meanTravelDistance(bool clearData = false);
    /// @brief Get the mean travel speed of the agents in \f$m/s\f$
    /// @param clearData If true, the travel times and distances are cleared after the computation
    /// @return Measurement<double> The mean travel speed of the agents and the standard deviation
    Measurement<double> meanTravelSpeed(bool clearData = false);
    /// @brief Get the turn counts of the agents
    /// @return const std::unordered_map<Id, std::unordered_map<Id, size_t>>& The turn counts. The outer map's key is the street id, the inner map's key is the next street id and the value is the number of counts
    inline std::unordered_map<Id, std::unordered_map<Id, size_t>> const& turnCounts()
        const noexcept {
      return m_turnCounts;
    };
    /// @brief Get the normalized turn counts of the agents
    /// @return const std::unordered_map<Id, std::unordered_map<Id, double>>& The normalized turn counts. The outer map's key is the street id, the inner map's key is the next street id and the value is the normalized number of counts
    std::unordered_map<Id, std::unordered_map<Id, double>> const normalizedTurnCounts()
        const noexcept;

    std::unordered_map<Id, std::array<long, 4>> turnMapping() const {
      return m_turnMapping;
    }

    /// @brief Get the origin counts of the agents
    /// @param bReset If true, the origin counts are cleared (default is true)
    tbb::concurrent_unordered_map<Id, std::size_t> originCounts(
        bool const bReset = true) noexcept;
    /// @brief Get the destination counts of the agents
    /// @param bReset If true, the destination counts are cleared (default is true)
    tbb::concurrent_unordered_map<Id, std::size_t> destinationCounts(
        bool const bReset = true) noexcept;

    /// @brief Get the mean density of the streets in \f$m^{-1}\f$
    /// @return Measurement<double> The mean density of the streets and the standard deviation
    Measurement<double> streetMeanDensity(bool normalized = false) const;
    /// @brief Get the mean flow of the streets in \f$s^{-1}\f$
    /// @return Measurement<double> The mean flow of the streets and the standard deviation
    Measurement<double> streetMeanFlow() const;
    /// @brief Get the mean flow of the streets in \f$s^{-1}\f$
    /// @param threshold The density threshold to consider
    /// @param above If true, the function returns the mean flow of the streets with a density above the threshold, otherwise below
    /// @return Measurement<double> The mean flow of the streets and the standard deviation
    Measurement<double> streetMeanFlow(double threshold, bool above) const;

    /// @brief Print a summary of the dynamics to an output stream
    /// @param os The output stream to write to (default is std::cout)
    /// @details The summary includes:
    /// - The RoadNetwork description (nodes, edges, capacity, intersections, traffic lights, roundabouts, coil sensors)
    /// - Number of inserted agents
    /// - Number of added agents
    /// - Number of arrived agents
    /// - Number of killed agents
    /// - Current number of agents in the simulation
    void summary(std::ostream& os = std::cout) const;
  };

  template <typename... TArgs>
  void FirstOrderDynamics::setSpeedFunction(SpeedFunction const speedFunction,
                                            TArgs&&... args) {
    switch (speedFunction) {
      case SpeedFunction::CUSTOM:
        // Assert that the only argument is a function with the correct signature
        if constexpr (sizeof...(args) != 1) {
          throw std::invalid_argument(std::format(
              "Custom speed function requires exactly one argument, but {} were provided",
              sizeof...(args)));
        } else if constexpr (!std::is_invocable_r_v<
                                 double,
                                 std::tuple_element_t<0, std::tuple<TArgs...>>,
                                 std::unique_ptr<Street> const&>) {
          throw std::invalid_argument(
              "Custom speed function requires a callable argument with signature "
              "double(std::unique_ptr<Street> const&)");
        } else {
          m_speedFunction = std::get<0>(std::forward_as_tuple(args...));
          m_speedFunctionDescription = "CUSTOM";
        }
        break;
      case SpeedFunction::LINEAR:
        // There should be only one argument, named "alpha", so check it and extract it
        if constexpr (sizeof...(args) != 1) {
          throw std::invalid_argument(std::format(
              "Linear speed function requires exactly one argument, but {} were provided",
              sizeof...(args)));
        } else if constexpr (!std::is_convertible_v<
                                 std::tuple_element_t<0, std::tuple<TArgs...>>,
                                 double>) {
          throw std::invalid_argument(std::format(
              "Linear speed function requires a double argument, but {} was provided",
              typeid(std::remove_cvref_t<std::tuple_element_t<0, std::tuple<TArgs...>>>)
                  .name()));
        } else {
          double alpha = std::get<0>(std::forward_as_tuple(args...));
          if (alpha < 0. || alpha >= 1.) {
            throw std::invalid_argument(
                std::format("The alpha parameter ({}) must be in [0., 1)", alpha));
          }
          m_speedFunction = [alpha](std::unique_ptr<Street> const& pStreet) {
            return pStreet->maxSpeed() * (1. - alpha * pStreet->density(true));
          };
          m_speedFunctionDescription = std::format("LINEAR(alpha={})", alpha);
        }
        break;
    }
  }

  template <typename TContainer>
    requires(std::is_convertible_v<typename TContainer::value_type, Id>)
  void FirstOrderDynamics::setDestinationNodes(TContainer const& destinationNodes) {
    m_itineraries.clear();
    auto const numNodes{destinationNodes.size()};
    m_destinationNodes.clear();
    m_destinationNodes.reserve(numNodes);
    std::for_each(destinationNodes.begin(),
                  destinationNodes.end(),
                  [this, &numNodes](auto const& nodeId) -> void {
                    this->m_destinationNodes.push_back({nodeId, 1. / numNodes});
                    this->addItinerary(nodeId, nodeId);
                  });
  }

  template <typename... TArgs>
    requires(std::is_constructible_v<Agent, Id, std::time_t, TArgs...>)
  void FirstOrderDynamics::addAgent(TArgs&&... args) {
    addAgent(std::make_unique<Agent>(
        this->m_nInsertedAgents, this->time_step(), std::forward<TArgs>(args)...));
  }

  template <typename... TArgs>
    requires(std::is_constructible_v<Agent, Id, std::time_t, TArgs...>)
  void FirstOrderDynamics::addAgents(std::size_t const nAgents, TArgs&&... args) {
    for (size_t i{0}; i < nAgents; ++i) {
      addAgent(std::make_unique<Agent>(
          this->m_nInsertedAgents, this->time_step(), std::forward<TArgs>(args)...));
    }
  }

  template <typename... TArgs>
    requires(std::is_constructible_v<Itinerary, TArgs...>)
  void FirstOrderDynamics::addItinerary(TArgs&&... args) {
    addItinerary(std::make_shared<Itinerary>(std::forward<TArgs>(args)...));
  }

}  // namespace dsf::mobility
