name: Test the installation on MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install tools manually
      run: brew install tbb

    - name: Set environment variables
      run: |
        echo "CPLUS_INCLUDE_PATH=$(brew --prefix tbb)/include" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$(brew --prefix tbb)/lib" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(brew --prefix tbb)/lib" >> $GITHUB_ENV

    - uses: actions/checkout@v4

    - name: Build and install
      working-directory: ${{github.workspace}}
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix tbb) -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        sudo cmake --install .

    - name: Test include
      working-directory: ${{github.workspace}}
      run: |
        touch test.cpp
        echo "#include <dsf/dsf.hpp>" >> test.cpp
        echo "int main() {}" >> test.cpp
        g++ test.cpp -std=c++20 -I$(brew --prefix tbb)/include -L$(brew --prefix tbb)/lib -ltbb \
          && echo "Compiled successfully" \
          || (echo "Cannot include dsf" ; exit 1)
