name: Run tests on MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install tools manually
      run: brew install tbb fmt spdlog

    - uses: actions/checkout@v4

    - name: Configure CMake
      working-directory: ${{github.workspace}}/test
      run: cmake -B ${{github.workspace}}/test/build

    - name: Build
      working-directory: ${{github.workspace}}/test
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/test/build

    - name: Run tests
      working-directory: ${{github.workspace}}/test
      run: ./dsf_tests.out
