name: Test the installation on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install tools manually
      run: sudo apt update && sudo apt install libtbb-dev libfmt-dev libspdlog-dev libsimdjson-dev
    - uses: actions/checkout@v4

    - name: Build and install
      working-directory: ${{github.workspace}}
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        sudo cmake --install .

    - name: Test include
      working-directory: ${{github.workspace}}
      run: |
        touch test.cpp
        echo "#include <dsf/dsf.hpp>" >> test.cpp
        echo "int main() {}" >> test.cpp
        g++ test.cpp -std=c++20 && echo "Compiled successfully" || echo "Cannot include dsf"
