name: Run tests

# The workflow gets triggered by pushes and pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    # Checks out the code in the repository
    - uses: actions/checkout@v3

    - name: Compile and run the C++ tests
      run: |
        cd test/ && make
        ./test.out
