name: Profile the execution time of a simulation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build test simulation
      working-directory: ${{github.workspace}}/profiling
      run: cmake -B build && make -C build

    - name: Generate the gprof file and re-run
      working-directory: ${{github.workspace}}/profiling
      run: |
        ./prof.out
        gprof -b ./prof.out
